Handle security issue with OT extension
aicis/fresco pull request #395
Opened 2022-07-08 12:32 UTC by jot2re

This closes issues #394 

The PR also includes minor changes suggested by the SonarLint plugin in order to improve the general code quality in the files touched.

2022-08-11 07:32 UTC, jonas-lj requested changes
Make sure to use the correct code style for all changed files. Otherwise it looks good.

2022-08-11 07:32 UTC, jonas-lj commented on tools/mascot/src/main/java/dk/alexandra/fresco/tools/mascot/MascotResourcePoolImpl.java
> +      if (getMyId() == otherId) {
Use the correct style

2022-08-11 07:32 UTC, jonas-lj commented on tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/otextension/RotFactory.java
> +      this.resources = resources;
Style

2022-08-11 07:32 UTC, jonas-lj commented on tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/otextension/RotFactory.java
> +    public RotSender createSender() {
Style

2022-08-11 07:32 UTC, jonas-lj commented on tools/ot/src/test/java/dk/alexandra/fresco/tools/ot/otextension/BristolRotBatchDemo.java
> +            amountOfOTs, messageSize);
Style

2022-08-11 07:32 UTC, jonas-lj commented on tools/ot/src/test/java/dk/alexandra/fresco/tools/ot/otextension/TestCote.java
> +import java.lang.reflect.Field;
Style

2022-08-11 07:32 UTC, jonas-lj commented on tools/ot/src/test/java/dk/alexandra/fresco/tools/ot/otextension/TestFunctionalBristolOt.java
> +      OtExtensionResourcePool resources = ctx.createResources(id);
Style

2022-08-23 15:29 UTC, jot2re commented
@jonas-lj requested changes have been added.

2022-08-26 11:10 UTC, jonas-lj approved these changes

2022-08-26 11:10 UTC, merged